import { PERMISSIONS, ROLES } from "./permissions";

export const rolePermissions = {
  [ROLES.ADMIN]: [
    PERMISSIONS.UPLOAD_REPORT,
    PERMISSIONS.APPROVE_MAINTENANCE,
    PERMISSIONS.EDIT_FLEET,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_USERS,
  ],

  [ROLES.TECHNICAL]: [
    PERMISSIONS.UPLOAD_REPORT,
    PERMISSIONS.REQUEST_MAINTENANCE, 
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EDIT_FLEET,
  ],


};
